# Generated by Django 2.2.5 on 2019-10-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
    ]
