# Generated by Django 2.2.5 on 2019-11-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedproduct',
            name='child_id',
        ),
        migrations.AddField(
            model_name='relatedproduct',
            name='main_product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='relatedproduct',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='relatedproduct',
            name='related_product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='relatedproduct',
            name='url_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
